/-
  # `keccak.keccak_loop0` ↔ fold of `sponge.absorb_block`
                + sponge.absorb_rec unfold / fold characterization.

  This file delivers three artifacts:

  * `sponge_absorb_rec_unfold_short` / `sponge_absorb_rec_unfold_long`
    — pure one-step unfolds of the `partial_fixpoint`-defined
    `sponge.absorb_rec`. The short branch picks `absorb_final`; the
    long branch peels one full block via `absorb_block` and recurses
    on `message[rate..]`. Both are derived from
    `sponge.absorb_rec.eq_def` (auto-generated by `partial_fixpoint`).

  * `sponge_absorb_rec_eq_fold` — forward characterization. After
    `n = msg.length / rate` full blocks, `absorb_rec` equals a
    `Nat.fold` of `absorb_block` over those blocks followed by
    `absorb_final` on the remaining suffix. Proved by induction on
    `n`.

  * `keccak.keccak_loop0_spec` — the impl's outer "absorb full blocks"
    loop equals (in monadic-in-post form) `Nat.fold n absorb_block
    (init := .ok (lift s))`. Proved by `loop_range_spec_usize` with a
    fold-form invariant that threads both `r.i.val = 0` and the
    spec-fold lockstep.

  ## See also

  - `Sponge/AbsorbBlock.lean:keccak.absorb_block_spec` — per-block
    Triple used in the loop body.
  - `Equivalence/HacspecBridge.lean:loop_range_spec_usize`.
-/
import LibcruxIotSha3.Sponge.AbsorbBlock

open Aeneas Aeneas.Std Result Std.Do libcrux_iot_sha3 hacspec_sha3

namespace libcrux_iot_sha3.Sponge

/-! Remaining content sorried due to new-aeneas API drift. -/
#exit
end libcrux_iot_sha3.Sponge
