-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_sha3]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace libcrux_iot_sha3

/-- [libcrux_traits::digest::Hasher]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libcrux-traits-0.0.6/src/digest.rs', lines 62:0-62:59
    Name pattern: [libcrux_traits::digest::Hasher]
    Visibility: public -/
@[rust_type "libcrux_traits::digest::Hasher"]
structure libcrux_traits.digest.Hasher (D : Type) (Clause0_IncrementalState :
  Type) (N : Std.Usize) where
  state : Clause0_IncrementalState

/-- [libcrux_iot_sha3::impl_digest_trait::Sha3_224]
    Source: 'sha3/src/impl_digest_trait.rs', lines 13:8-13:25
    Visibility: public -/
@[reducible]
def impl_digest_trait.Sha3_224 := Unit

/-- [libcrux_iot_sha3::impl_digest_trait::Sha3_256]
    Source: 'sha3/src/impl_digest_trait.rs', lines 13:8-13:25
    Visibility: public -/
@[reducible]
def impl_digest_trait.Sha3_256 := Unit

/-- [libcrux_iot_sha3::impl_digest_trait::Sha3_384]
    Source: 'sha3/src/impl_digest_trait.rs', lines 13:8-13:25
    Visibility: public -/
@[reducible]
def impl_digest_trait.Sha3_384 := Unit

/-- [libcrux_iot_sha3::impl_digest_trait::Sha3_512]
    Source: 'sha3/src/impl_digest_trait.rs', lines 13:8-13:25
    Visibility: public -/
@[reducible]
def impl_digest_trait.Sha3_512 := Unit

/-- [libcrux_iot_sha3::lane::Lane2U32]
    Source: 'sha3/src/lane.rs', lines 7:0-7:41
    Visibility: public -/
@[reducible]
def lane.Lane2U32 := Array Std.U32 2#usize

/-- [libcrux_iot_sha3::state::KeccakState]
    Source: 'sha3/src/state.rs', lines 13:0-18:1 -/
structure state.KeccakState where
  st : Array lane.Lane2U32 25#usize
  c : Array lane.Lane2U32 5#usize
  d : Array lane.Lane2U32 5#usize
  i : Std.Usize

/-- [libcrux_iot_sha3::keccak::KeccakXofState]
    Source: 'sha3/src/keccak.rs', lines 14:0-25:1 -/
structure keccak.KeccakXofState (RATE : Std.Usize) where
  inner : state.KeccakState
  buf : Array Std.U8 RATE
  buf_len : Std.Usize
  sponge : Bool

/-- [libcrux_iot_sha3::Algorithm]
    Source: 'sha3/src/lib.rs', lines 78:0-90:1
    Visibility: public -/
@[discriminant u32 [1,2,3,4]]
inductive Algorithm where
| Sha224 : Algorithm
| Sha256 : Algorithm
| Sha384 : Algorithm
| Sha512 : Algorithm

/-- Trait declaration: [libcrux_iot_sha3::incremental::private::Sealed]
    Source: 'sha3/src/lib.rs', lines 376:8-376:27
    Visibility: public -/
structure incremental.private.Sealed (Self : Type) where

/-- [libcrux_iot_sha3::incremental::Shake128Xof]
    Source: 'sha3/src/lib.rs', lines 383:4-385:5
    Visibility: public -/
structure incremental.Shake128Xof where
  state : keccak.KeccakXofState 168#usize

/-- [libcrux_iot_sha3::incremental::Shake256Xof]
    Source: 'sha3/src/lib.rs', lines 388:4-390:5
    Visibility: public -/
structure incremental.Shake256Xof where
  state : keccak.KeccakXofState 136#usize

/-- Trait declaration: [libcrux_iot_sha3::incremental::Xof]
    Source: 'sha3/src/lib.rs', lines 395:4-434:5
    Visibility: public -/
structure incremental.Xof (Self : Type) (RATE : Std.Usize) where
  privateSealedInst : incremental.private.Sealed Self
  new : Result Self
  absorb : Self → Slice Std.U8 → Result Self
  absorb_final : Self → Slice Std.U8 → Result Self
  squeeze : Self → Slice Std.U8 → Result (Self × (Slice Std.U8))

end libcrux_iot_sha3
