name = "LibcruxIotSha3"
version = "0.1.0"
defaultTargets = ["LibcruxIotSha3"]

[[lean_lib]]
name = "LibcruxIotSha3"
globs = ["LibcruxIotSha3", "LibcruxIotSha3.+"]

[[require]]
name = "Hax"
git = { url = "https://github.com/cryspen/hax-evit", subDir = "hax-lib/proof-libs/aeneas-lean" }
rev = "af5a2829a52005bf38e023b4370ff6e6ae694da6"

[[require]]
name = "HacspecSha3"
git = { url = "https://github.com/abentkamp/libcrux-for-claude", subDir = "specs/sha3/proofs/aeneas-lean" }
rev = "163f227bbaa6ce4d8a1ab7326cb592eedcf8bd3f"
